### ISSUE TITLE
Refactor and Cleanup

### ISSUE THREAD

**Issue by hyperdriveguy** [nephitejnf/muse2pokecrystal#11]
Before I get around to documenting my new changes, it's worth mentioning that he code is currently pretty messy and a little redundant in some places. Hopefully this will make the code smaller, more readable, and less prone to errors.
# Tasks
- [x] Split up code into more digestible pieces
  - [x] Split out most of the text
  - [x] Extract reusable data
  - [x] Refactor all of the channel parsing into a single class
  - [x] Refactor `process_score` into a class
  - [x] Related functions in their own files
- [x] More breakpoints and smart rerunning (affects user defined loops)
- [x] Get rid of unnecessary parameters in functions
- [x] Conform to most of the PEP standards (`note_print` says hi)
